name: Update README Stats
on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch:     # Allows you to run it manually

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
      - name: Generate Stats Card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=Sumiksh&show_icons=true&theme=dracula
          path: profile/stats.svg
      - name: Generate Language Card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=Sumiksh&theme=gruvbox
          path: profile/langs.svg
      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update stats" || exit 0
          git push